const GET_JOKES_ENDPOINT = 'http://api.icndb.com/jokes/random';
const ADD_FAVOURITE_JOKE = 'ADD_FAVOURITE_JOKE';
const REMOVE_FAVOURITE_JOKE = 'REMOVE_FAVOURITE_JOKE';
const FETCH_JOKES_START = 'FETCH_JOKES_START';
const FETCH_JOKES_FAIL = 'FETCH_JOKES_FAIL';
const FETCH_JOKES_SUCCESS = 'FETCH_JOKES_SUCCESS';
const FETCH_FAVOURITE_START = 'FETCH_FAVOURITE_START';
const FETCH_FAVOURITE_FAIL = 'FETCH_FAVOURITE_FAIL';
const FETCH_FAVOURITE_SUCCESS = 'FETCH_FAVOURITE_SUCCESS';
const AUTH_SUCCESSFUL = 'AUTH_SUCCESSFUL';
const AUTH_LOGOUT = 'AUTH_LOGOUT';
const MAX_JOKES = 10;

export {
    GET_JOKES_ENDPOINT,
    ADD_FAVOURITE_JOKE,
    REMOVE_FAVOURITE_JOKE,
    FETCH_FAVOURITE_START,
    FETCH_FAVOURITE_FAIL,
    FETCH_FAVOURITE_SUCCESS,
    FETCH_JOKES_FAIL,
    FETCH_JOKES_START,
    FETCH_JOKES_SUCCESS,
    AUTH_LOGOUT,
    AUTH_SUCCESSFUL,
    MAX_JOKES
};